
/*******************************************************************************
* generated by lcd-image-converter rev.90f620c from 2017-10-04 21:09:44 +0500
* font
* filename: C:/Users/Kitano/YandexDisk/Наручные часы/Плата F030/Font18.xml
* name: Font18
* family: MS Shell Dlg 2
* size: 14
* style: Обычный
* included characters:  ,-.0123456789:%ABCDEFGHIJKLMNOPQRSTUVWXYZmcha
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
	 
	 uint8_t
*/

#include <stdint.h>
#include "LCD.h"



#if (0x0 == 0x0)
static const char image_data_Font18_0x20[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x20 = { image_data_Font18_0x20,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x25[28] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███∙∙∙∙█∙∙∙∙
    // ∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙█∙∙∙█∙█∙∙∙∙∙∙
    // ∙█∙∙∙█∙█∙███∙∙
    // ∙∙███∙█∙█∙∙∙█∙
    // ∙∙∙∙∙∙█∙█∙∙∙█∙
    // ∙∙∙∙∙█∙∙█∙∙∙█∙
    // ∙∙∙∙∙█∙∙█∙∙∙█∙
    // ∙∙∙∙█∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x0e, 0x10, 0x44, 0x81, 0x12, 0x04, 0x50, 0x11, 0x5c, 0x3a, 0x88, 0x0a, 0x20, 0x48, 0x81, 0x22, 0x08, 0x70, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x25 = { image_data_Font18_0x25,
    14, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x2c[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // ∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x22, 0x40
};
static const tImage Font18_0x2c = { image_data_Font18_0x2c,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x2d[10] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x2d = { image_data_Font18_0x2d,
    5, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x2e[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x40, 0x00
};
static const tImage Font18_0x2e = { image_data_Font18_0x2e,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x30[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙∙∙
    // ∙█∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x38, 0x44, 0x82, 0x82, 0x82, 0x82, 0x82, 0x82, 0x44, 0x38, 0x00, 0x00, 0x00
};
static const tImage Font18_0x30 = { image_data_Font18_0x30,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x31[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x08, 0x38, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x3e, 0x00, 0x00, 0x00
};
static const tImage Font18_0x31 = { image_data_Font18_0x31,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x32[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x3c, 0x42, 0x02, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x7e, 0x00, 0x00, 0x00
};
static const tImage Font18_0x32 = { image_data_Font18_0x32,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x33[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙███∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x3c, 0x42, 0x02, 0x02, 0x1c, 0x02, 0x02, 0x02, 0x42, 0x3c, 0x00, 0x00, 0x00
};
static const tImage Font18_0x33 = { image_data_Font18_0x33,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x34[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // █∙∙∙∙█∙∙
    // ███████∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x04, 0x0c, 0x14, 0x24, 0x44, 0x84, 0xfe, 0x04, 0x04, 0x04, 0x00, 0x00, 0x00
};
static const tImage Font18_0x34 = { image_data_Font18_0x34,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x35[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x7e, 0x40, 0x40, 0x40, 0x7c, 0x02, 0x02, 0x02, 0x42, 0x3c, 0x00, 0x00, 0x00
};
static const tImage Font18_0x35 = { image_data_Font18_0x35,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x36[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙███∙∙
    // ∙██∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █████∙∙∙
    // █∙∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x1c, 0x60, 0x40, 0x80, 0xf8, 0x84, 0x82, 0x82, 0x44, 0x38, 0x00, 0x00, 0x00
};
static const tImage Font18_0x36 = { image_data_Font18_0x36,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x37[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x7e, 0x02, 0x04, 0x04, 0x04, 0x08, 0x08, 0x10, 0x10, 0x20, 0x00, 0x00, 0x00
};
static const tImage Font18_0x37 = { image_data_Font18_0x37,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x38[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█████∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█████∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x7c, 0x82, 0x82, 0x82, 0x7c, 0x82, 0x82, 0x82, 0x82, 0x7c, 0x00, 0x00, 0x00
};
static const tImage Font18_0x38 = { image_data_Font18_0x38,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x39[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙∙∙
    // ∙█∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x38, 0x44, 0x82, 0x82, 0x42, 0x3e, 0x02, 0x04, 0x0c, 0x70, 0x00, 0x00, 0x00
};
static const tImage Font18_0x39 = { image_data_Font18_0x39,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x3a[10] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x10, 0x80, 0x00, 0x00, 0x42, 0x00, 0x00
};
static const tImage Font18_0x3a = { image_data_Font18_0x3a,
    5, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x41[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙█∙∙∙█∙∙
    // ∙█████∙∙
    // ∙█∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x10, 0x28, 0x28, 0x28, 0x28, 0x44, 0x7c, 0x44, 0x82, 0x82, 0x00, 0x00, 0x00
};
static const tImage Font18_0x41 = { image_data_Font18_0x41,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x42[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █████∙∙∙
    // █∙∙∙∙█∙∙
    // █∙∙∙∙█∙∙
    // █∙∙∙∙█∙∙
    // █████∙∙∙
    // █∙∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙█∙∙
    // █████∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0xf8, 0x84, 0x84, 0x84, 0xf8, 0x84, 0x82, 0x82, 0x84, 0xf8, 0x00, 0x00, 0x00
};
static const tImage Font18_0x42 = { image_data_Font18_0x42,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x43[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙
    // ∙██∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙██∙∙∙∙█∙
    // ∙∙∙████∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x03, 0xc6, 0x12, 0x02, 0x01, 0x00, 0x80, 0x40, 0x10, 0x0c, 0x21, 0xe0, 0x00, 0x00, 0x00
};
static const tImage Font18_0x43 = { image_data_Font18_0x43,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x44[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ██████∙∙∙∙
    // █∙∙∙∙∙██∙∙
    // █∙∙∙∙∙∙█∙∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙∙
    // █∙∙∙∙∙██∙∙
    // ██████∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x03, 0xf0, 0x83, 0x20, 0x48, 0x0a, 0x02, 0x80, 0xa0, 0x28, 0x12, 0x0c, 0xfc, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x44 = { image_data_Font18_0x44,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x45[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ███████∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // ███████∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // ███████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0xfe, 0x80, 0x80, 0x80, 0xfe, 0x80, 0x80, 0x80, 0x80, 0xfe, 0x00, 0x00, 0x00
};
static const tImage Font18_0x45 = { image_data_Font18_0x45,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x46[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ██████∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // ██████∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x07, 0xe8, 0x10, 0x20, 0x7e, 0x81, 0x02, 0x04, 0x08, 0x00, 0x00, 0x00
};
static const tImage Font18_0x46 = { image_data_Font18_0x46,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x47[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙
    // ∙██∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙∙
    // █∙∙∙████∙
    // █∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙██∙∙∙∙█∙
    // ∙∙∙████∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x03, 0xc6, 0x12, 0x02, 0x01, 0x00, 0x8f, 0x40, 0x90, 0x4c, 0x21, 0xe0, 0x00, 0x00, 0x00
};
static const tImage Font18_0x47 = { image_data_Font18_0x47,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x48[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // ████████∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x10, 0x28, 0x14, 0x0a, 0x05, 0xfe, 0x81, 0x40, 0xa0, 0x50, 0x28, 0x10, 0x00, 0x00, 0x00
};
static const tImage Font18_0x48 = { image_data_Font18_0x48,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x49[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ███∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 0x0e, 0x44, 0x44, 0x44, 0x44, 0xe0, 0x00
};
static const tImage Font18_0x49 = { image_data_Font18_0x49,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x4a[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00, 0x00, 0x1e, 0x08, 0x20, 0x82, 0x08, 0x20, 0x82, 0xf0, 0x00, 0x00
};
static const tImage Font18_0x4a = { image_data_Font18_0x4a,
    6, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x4b[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙█∙∙
    // █∙∙∙█∙∙∙
    // █∙∙█∙∙∙∙
    // █∙█∙∙∙∙∙
    // ███∙∙∙∙∙
    // █∙∙█∙∙∙∙
    // █∙∙∙█∙∙∙
    // █∙∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x82, 0x84, 0x88, 0x90, 0xa0, 0xe0, 0x90, 0x88, 0x84, 0x82, 0x00, 0x00, 0x00
};
static const tImage Font18_0x4b = { image_data_Font18_0x4b,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x4c[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // ██████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x04, 0x08, 0x10, 0x20, 0x40, 0x81, 0x02, 0x04, 0x0f, 0xc0, 0x00, 0x00
};
static const tImage Font18_0x4c = { image_data_Font18_0x4c,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x4d[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙██∙
    // ██∙∙∙∙∙██∙
    // █∙█∙∙∙█∙█∙
    // █∙█∙∙∙█∙█∙
    // █∙∙█∙█∙∙█∙
    // █∙∙█∙█∙∙█∙
    // █∙∙∙█∙∙∙█∙
    // █∙∙∙█∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x03, 0x06, 0xc1, 0xa8, 0xaa, 0x2a, 0x52, 0x94, 0xa2, 0x28, 0x8a, 0x02, 0x80, 0x80, 0x00, 0x00, 0x00
};
static const tImage Font18_0x4d = { image_data_Font18_0x4d,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x4e[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙█∙
    // ██∙∙∙∙∙█∙
    // █∙█∙∙∙∙█∙
    // █∙█∙∙∙∙█∙
    // █∙∙█∙∙∙█∙
    // █∙∙∙█∙∙█∙
    // █∙∙∙█∙∙█∙
    // █∙∙∙∙█∙█∙
    // █∙∙∙∙∙██∙
    // █∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x18, 0x2c, 0x15, 0x0a, 0x85, 0x22, 0x89, 0x44, 0xa1, 0x50, 0x68, 0x30, 0x00, 0x00, 0x00
};
static const tImage Font18_0x4e = { image_data_Font18_0x4e,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x4f[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙███∙∙∙∙
    // ∙██∙∙∙██∙∙
    // ∙█∙∙∙∙∙█∙∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙∙
    // ∙██∙∙∙██∙∙
    // ∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x70, 0x63, 0x10, 0x48, 0x0a, 0x02, 0x80, 0xa0, 0x24, 0x11, 0x8c, 0x1c, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x4f = { image_data_Font18_0x4f,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x50[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █████∙∙∙
    // █∙∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙█∙∙
    // █████∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0xf8, 0x84, 0x82, 0x82, 0x84, 0xf8, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00, 0x00
};
static const tImage Font18_0x50 = { image_data_Font18_0x50,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x51[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙███∙∙∙∙
    // ∙██∙∙∙██∙∙
    // ∙█∙∙∙∙∙█∙∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙∙
    // ∙██∙∙∙██∙∙
    // ∙∙∙███∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙███∙
    0x00, 0x00, 0x00, 0x00, 0x70, 0x63, 0x10, 0x48, 0x0a, 0x02, 0x80, 0xa0, 0x24, 0x11, 0x8c, 0x1c, 0x01, 0x00, 0x40, 0x0e
};
static const tImage Font18_0x51 = { image_data_Font18_0x51,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x52[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █████∙∙∙∙
    // █∙∙∙∙█∙∙∙
    // █∙∙∙∙█∙∙∙
    // █∙∙∙∙█∙∙∙
    // █∙∙∙∙█∙∙∙
    // █████∙∙∙∙
    // █∙∙∙█∙∙∙∙
    // █∙∙∙∙█∙∙∙
    // █∙∙∙∙∙█∙∙
    // █∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x1f, 0x08, 0x44, 0x22, 0x11, 0x08, 0xf8, 0x44, 0x21, 0x10, 0x48, 0x10, 0x00, 0x00, 0x00
};
static const tImage Font18_0x52 = { image_data_Font18_0x52,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x53[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█████∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // ∙███∙∙∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x7c, 0x82, 0x80, 0x80, 0x70, 0x0c, 0x02, 0x02, 0x82, 0x7c, 0x00, 0x00, 0x00
};
static const tImage Font18_0x53 = { image_data_Font18_0x53,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x54[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ████████
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0xff, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x00, 0x00, 0x00
};
static const tImage Font18_0x54 = { image_data_Font18_0x54,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x55[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // █∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙∙
    // ∙∙████∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x10, 0x28, 0x14, 0x0a, 0x05, 0x02, 0x81, 0x40, 0xa0, 0x48, 0x43, 0xc0, 0x00, 0x00, 0x00
};
static const tImage Font18_0x55 = { image_data_Font18_0x55,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x56[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x82, 0x82, 0x44, 0x44, 0x44, 0x28, 0x28, 0x28, 0x10, 0x10, 0x00, 0x00, 0x00
};
static const tImage Font18_0x56 = { image_data_Font18_0x56,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x57[28] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙█∙∙∙∙∙█∙
    // █∙∙∙∙█∙█∙∙∙∙█∙
    // ∙█∙∙∙█∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙█∙∙∙█∙∙
    // ∙█∙∙█∙∙∙█∙∙█∙∙
    // ∙∙█∙█∙∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙█∙█∙∙∙
    // ∙∙██∙∙∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x82, 0x85, 0x09, 0x14, 0x44, 0x51, 0x11, 0x44, 0x48, 0x90, 0xa2, 0x82, 0x8a, 0x0c, 0x18, 0x10, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x57 = { image_data_Font18_0x57,
    14, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x58[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x82, 0x44, 0x44, 0x28, 0x10, 0x10, 0x28, 0x44, 0x44, 0x82, 0x00, 0x00, 0x00
};
static const tImage Font18_0x58 = { image_data_Font18_0x58,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x59[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x82, 0x44, 0x44, 0x28, 0x28, 0x10, 0x10, 0x10, 0x10, 0x10, 0x00, 0x00, 0x00
};
static const tImage Font18_0x59 = { image_data_Font18_0x59,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x5a[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ███████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // ███████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0xfe, 0x02, 0x04, 0x08, 0x10, 0x10, 0x20, 0x40, 0x80, 0xfe, 0x00, 0x00, 0x00
};
static const tImage Font18_0x5a = { image_data_Font18_0x5a,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x61[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙████∙
    // ∙█∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙██∙
    // ∙███∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x07, 0x11, 0x02, 0x3c, 0x8a, 0x14, 0x67, 0x40, 0x00, 0x00
};
static const tImage Font18_0x61 = { image_data_Font18_0x61,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x63[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x07, 0x11, 0x40, 0x81, 0x02, 0x02, 0x23, 0x80, 0x00, 0x00
};
static const tImage Font18_0x63 = { image_data_Font18_0x63,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x68[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙
    // █∙████∙∙
    // ██∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x80, 0x80, 0x80, 0xbc, 0xc2, 0x82, 0x82, 0x82, 0x82, 0x82, 0x82, 0x00, 0x00, 0x00
};
static const tImage Font18_0x68 = { image_data_Font18_0x68,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const char image_data_Font18_0x6d[24] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙█∙██∙∙██∙∙∙
    // ∙██∙∙██∙∙█∙∙
    // ∙█∙∙∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x98, 0x66, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x44, 0x40, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font18_0x6d = { image_data_Font18_0x6d,
    12, 16, 8};
#endif


static const tChar Font18_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font18_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font18_0x25},
#else
  // character: '%' == ''
  {0x25, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font18_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font18_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font18_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font18_0x30},
#else
  // character: '0' == ''
  {0x30, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font18_0x31},
#else
  // character: '1' == ''
  {0x31, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font18_0x32},
#else
  // character: '2' == ''
  {0x32, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font18_0x33},
#else
  // character: '3' == ''
  {0x33, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font18_0x34},
#else
  // character: '4' == ''
  {0x34, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font18_0x35},
#else
  // character: '5' == ''
  {0x35, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font18_0x36},
#else
  // character: '6' == ''
  {0x36, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font18_0x37},
#else
  // character: '7' == ''
  {0x37, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font18_0x38},
#else
  // character: '8' == ''
  {0x38, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font18_0x39},
#else
  // character: '9' == ''
  {0x39, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font18_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font18_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font18_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font18_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font18_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font18_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font18_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font18_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font18_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font18_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font18_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font18_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font18_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font18_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font18_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font18_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font18_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font18_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font18_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font18_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font18_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font18_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font18_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font18_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font18_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font18_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font18_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font18_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font18_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font18_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font18_0x},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font18_0x6d}
#else
  // character: 'm' == ''
  {0x6d, &Font18_0x}
#endif

};


const tFont Font18 = { 46, Font18_array };

